<?php
declare(strict_types=1);
/**
 * Square favicons (generated by scripts/generate-square-favicons.ps1) + cache-bust.
 * Paths come from includes/public_paths.php (set $layoutBase before first favicon/header/footer include).
 */
require_once __DIR__ . '/public_paths.php';
$brandDir = dirname(__DIR__) . '/assets/images/brand';
$v = is_file($brandDir . '/favicon-32.png') ? filemtime($brandDir . '/favicon-32.png') : time();
$vq = rawurlencode((string)$v);
$b = htmlspecialchars($faviconHrefBase, ENT_QUOTES, 'UTF-8');
?>
    <link rel="icon" type="image/png" sizes="32x32" href="<?= $b ?>favicon-32.png?v=<?= $vq ?>">
    <link rel="icon" type="image/png" sizes="16x16" href="<?= $b ?>favicon-16.png?v=<?= $vq ?>">
    <link rel="apple-touch-icon" sizes="180x180" href="<?= $b ?>apple-touch-icon.png?v=<?= $vq ?>">
